export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_ALL_USERS = "SET_ALL_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const SET_MY_PROJECTS = "SET_MY_PROJECTS";
export const SET_MY_TEAMS = "SET_MY_TEAMS";
export const UPDATE_TASK = "UPDATE_TASK";
export const SET_CURRENT_PROJECT_USER  = "SET_CURRENT_PROJECT_USER ";
export const SET_MY_MESSAGES = "SET_MY_MESSAGES";
export const SET_INFORMATION_OTHER = "SET_INFORMATION_OTHER";
export const CHANGE_STATUS_MESSAGE = "CHANGE_STATUS_MESSAGE";
export const ADD_MESSAGE_TO_CONVERSATION = "ADD_MESSAGE_TO_CONVERSATION";
export const ADD_NEW_CONVERSATION = "ADD_NEW_CONVERSATION";
export const ADD_EMPLOYE   = "ADD_EMPLOYE";
export const SEARCH_EMPLOYES   = "SEARCH_EMPLOYES";
export const SEARCH_AFFECTATION = "SEARCH_AFFECTATION"  ; 
export const SET_MY_PROJECTS_ACHEIVED = "SET_PROJECTS_ACHEIVED"  ; 
export const SET_MY_PROJECT_WORKING = "SET_PROJECT_WORKING"  ; 

export const SET_SHOW_SIDE_BARE = "SET_SHOW_SIDE_BAR";


///////// ROLES ///////////
export const SET_ROLES = "SET_ROLES"  ; 
///////// EMPLOYE /////////

export const SET_EMPLOYES = "SET_EMPLOYES";
export const SET_CHEF_PROJECTS = "SET_CHEF_PROJECTS";
export const SET_SIMPLE_EMPLOYES = "SET_SIMPLE_EMPLOYES";
export const SET_ADMINS = "SET_ADMINS";
export const SEARCH_ADMINS = "SEARCH_ADMINS";
export const SEARCH_CHEF = "SEARCH_CHEF";
export const SEARCH_SIMPLE = "SEARCH_SIMPLE";
export const CLEAR_SEARCH_EMPLOYES = "CLEAR_SEARCH_EMPLOYES";
export const REMOVE_EMPLOYE = "REMOVE_EMPLOYE";


//////// PROJECT ///////////

export const SET_NEW_PROJECT = "SET_NEW_PROJECT" ;
export const SET_PROJECTS = "SET_PROJECTS" ;
export const  REMOVE_PROJECT = " REMOVE_PROJECT" ; 
export const  VALIDATE_PROJECT = " VALIDATE_PROJECT" ; 
export const SET_PROJECTS_PENDING = "SET_PROJECTS_PENDING" ;
export const SET_PROJECTS_WORKING = "SET_PROJECTS_WORKING" ;
export const SET_PROJECTS_FINISHED = "SET_PROJECTS_FINISHED" ;
export const SET_PROJECT = "SET_PROJECT";
export const ADD_TASKS_TO_PROJECT = "ADD_TASKS_TO_PROJECT";
export const ADD_TASKS_TO_PROJECTS = "ADD_TASKS_TO_PROJECTS";
export const SET_PROJECTS_CURRENT_USER = "SET_PROJECTS_CURRENT_USER";
export const SET_PROJECTS_SEARCHED = "SET_PROJECTS_SEARCHED";
export const ADD_MEMBER_TO_PROJECT = "ADD_MEMBER_TO_PROJECT";
export const ADD_CHEF_TO_PROJECT = "ADD_CHEF_TO_PROJECT";
export const ADD_CLIENT_TO_PROJECT = "ADD_CLIENT_TO_PROJECT"; 
export const SET_PROJECT_FROM_SERVER = "SET_PROJECT_FROM_SERVER"; 
export const ADD_CATEGORY_TO_PROJECT = "ADD_CATEGORY_TO_PROJECT"; 
export const SET_PROJECTS_WORKING_SEARCHED = "SET_PROJECTS_WORKING_SEARCHED"; 
export const SET_PROJECTS_COMPLETED_SEARCHED = "SET_PROJECTS_COMPLETED_SEARCHED"; 
export const SET_PROJECTS_PENDING_SEARCHED = "SET_PROJECTS_PENDING_SEARCHED"; 
export const CLEAR_PROJECTS_SEARCHED = "CLEAR_PROJECTS_SEARCHED"; 
export const VALIDATE_TASK = "VALIDATE_TASK"; 
export const  REMOVE_TASK_FROM_PROJECT = "REMOVE_TASK_FROM_PROJECT"; 
export const  ON_ACCEPT_USER = "ON_ACCEPT_USER"; 
export const  ON_REJECT_USER = "ON_REJECT_USER"; 
export const  ADD_MEMBER_TO_PENDING_LIST = "ADD_MEMBER_TO_PENDING_LIST"; 
export const  REMOVE_EMPLOYE_FROM_TEAM = "REMOVE_EMPLOYE_FROM_TEAM"; 
export const  SAVE_CATEGORY = "SAVE_CATEGORY"; 

////// TEAMS ///////////

export const SET_TEAMS = "SET_TEAMS";
export const SET_TEAM = "SET_TEAM";
export const SET_NEW_TEAM = "SET_NEW_TEAM";
export const SET_NEW_MEMBER_TO_TEAM = "SET_NEW_MEMBER_TO_TEAM";

////// CLIENTS ///////

export const SET_CLIENTS = "SET_CLIENTS" ; 
export const SEARCH_CLIENT = "SEARCH_CLIENT" ; 
export const ADD_CLIENT = "ADD_CLIENT";
export const SAVE_CLIENT = "SAVE_CLIENT";


//// FUNCTIONS //////
export const SET_FUNCTIONS = "SET_FUNCTIONS";
export const ADD_FUNCTION = "ADD_FUNCTION";


//////: TASKS ///////////
export const SET_PENDING_TASKS = "SET_PENDING_TASKS";
export const SET_WORKING_TASKS = "SET_WORKING_TASKS";
export const SET_TERMINATED_TASKS = "SET_TERMINATED_TASKS";
export const SET_EMPLOYE_TACH = "SET_EMPLOYE_TACH";
export const SET_TASKS = "SET_TASKS";
export const ADD_TASK = "ADD_TASK";
export const SET_CURRENT_USER_OF_TASK = "SET_CURRENT_USER_OF_TASK";

export const REMOVE_FROM_TASK_PENDING = "REMOVE_FROM_TASK_PENDING";
export const SEARCH_TASK = "SEARCH_TASK";

//////// SAVE TEAM /////////
export const SAVE_TEAM = "SAVE_TEAM";
export const CLEAR_TEAM = "CLEAR_TEAM";

//////// CATEGORIES /////////
export const SET_CATEGORIES = "SET_CATEGORIES";


////// 

export const SET_IMAGE_VARIABLE= "SET_IMAGE_VARIABLE";
export const CLEAR_VARIABLE_IMAGE = "CLEAR_VARIABLE_IMAGE"  ;